# Generated by Django 3.2.5 on 2022-08-21 10:09

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbackup',
            name='successful_at',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
