# Generated by Django 3.2.5 on 2022-08-21 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskbackup_successful_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbackup',
            name='enqueued_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 11, 58, 10, 892982)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskbackup',
            name='received_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 11, 58, 23, 618122)),
            preserve_default=False,
        ),
    ]
